<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <?php echo $this->HeadMeta(); ?> 
    <?php echo $this->headTitle(); ?> 
    <?php echo $this->headLink(); ?> 
    <?php echo $this->headScript(); ?>
</head>
<body>
    <?php echo $this->render('_header.phtml'); ?>
    <?php echo $this->layout()->menu; ?>

    <div id="container">
        <div id="content" class="column"><div id="pad">

            <?php echo $this->layout()->content; ?>

        </div></div>

        <div id="right" class="column">
            <?php echo $this->render('_search.phtml'); ?>
            <?php echo $this->layout()->advert; ?>
        </div>
    </div>
    <?php echo $this->render('_footer.phtml'); ?>

</body>
</html>

