<h1><?php echo $this->escape($this->title);?></h1>
<p><em>Places to take the kids</em> is a website that provides
information on places to take children for a good day out.
Every place featured on this site has been reviewed by people like you, 
so you'll be able to make informed decisions with no marketing waffle!
</p>
<p>This site is the worked example used in 
<a href="http://www.zendframeworkinaction.com"><em>Zend Framework in 
Action</em></a>, a book by Rob Allen, Nick Lo and Steven Brown. It is
published by Manning Publications.</p>