<h1>Log in</h1>
<p>Please log in here</p>
<?php echo $this->actionErrors();?>
<form method="POST" action="<?php echo $this->url(array('controller'=>'auth', 'action'=>'identify')); ?>"
    name="login" id="login-form">
    <div>
        <label>Username</label>
        <input type="text" name="username" value="" />
    </div>
    <div>
        <label>Password</label>
        <input type="password" name="password" value="" />
    </div>
    <div id="submit">
        <input type="submit" name="login" value="Login" />
    </div>
</form>