<h1><?php echo $this->videoEntry->mediaGroup->title->text; ?></h1>
<object width="425" height="355">
    <param name="movie" value="http://www.youtube.com/v/<?php echo $this->videoId; ?>&rel=0&color1=0x006699&color2=0x54abd6"></param>
    <param name="wmode" value="transparent"></param>
    <embed src="http://www.youtube.com/v/<?php echo $this->videoId; ?>&rel=0&color1=0x006699&color2=0x54abd6" type="application/x-shockwave-flash" wmode="transparent" width="425" height="355"></embed>
</object>
